services:
  cultivation-app-frontend:
    container_name: cultivation-app-frontend
    image: cultivation-app-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        - VITE_API_URL=http://localhost:3000/api
    ports: 
      - '80:80'